export const PARTNERS = [
  "HRWG",
  "SPF",
  "Tenaganita",
  "Autonomous 8",
  "HOME Singapore",
  "SPA",
  "Empowerment Through Art",
  "IMA",
  "Migrante International",
  "Kakehashi",
  "PERTIMIG",
  "ATKI",
  "WBI",
  "APMM",
  "Beranda Migran",
  "MMN",
  "GANAS",
  "IOJI",
  "IOM",
  "Paramadina University",
  "TAEF",
  "TFD",
  "Hurights Osaka",
  "Stella Maris Thailand",
  "Greenpeace",
  "SBMI",
  "CSP",
  "TETO",
  "Mae Fah Luang University",
  "Mindanao State University - General Santos City",
  "ASEAN Study Centre (Pusat Studi ASEAN) - Mataram University",
  "PSP",
  "JBMI",
  "New Naratif",
  "EJF Thailand",
];
